// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmeLAW7c8csp-a94cGqbgc4xrGVQ_UwVQ',
    appId: '1:904024544713:web:890c749368b457fb010418',
    messagingSenderId: '904024544713',
    projectId: 'whatsapp--backend-b7cdd',
    authDomain: 'whatsapp--backend-b7cdd.firebaseapp.com',
    storageBucket: 'whatsapp--backend-b7cdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJeqvfSA8NxDl9TRIHpXOgCcVhte6LhDc',
    appId: '1:904024544713:android:cfbb2c85443c7c2f010418',
    messagingSenderId: '904024544713',
    projectId: 'whatsapp--backend-b7cdd',
    storageBucket: 'whatsapp--backend-b7cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFPuzZEQQkPp88FVuk-u94TeDdUHd-Hg',
    appId: '1:904024544713:ios:9cc9a2543d985648010418',
    messagingSenderId: '904024544713',
    projectId: 'whatsapp--backend-b7cdd',
    storageBucket: 'whatsapp--backend-b7cdd.appspot.com',
    iosClientId: '904024544713-c5uhak0kfn06rmfc7biitcv2rqvb0stj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
